version: '2'
services:
  node:
    build: .
    image: node
    container_name: wa-node
    volumes:
      - $PWD:/code
    ports:
      - 8000:3000 
    links:
      - mysql
      - redis
  mysql:
    image: mysql
    container_name: wa-mysql
    volumes:
      - $PWD/docker/storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 8001:3306
  redis:
    image: redis
    container_name: wa-redis
    ports:
      - 8002:6379
  





